//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.People
{
    [Serializable]
    public class PeopleMsg : Message
    {
        public const string k_RosMessageName = "people_msgs/People";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public PersonMsg[] people;

        public PeopleMsg()
        {
            this.header = new HeaderMsg();
            this.people = new PersonMsg[0];
        }

        public PeopleMsg(HeaderMsg header, PersonMsg[] people)
        {
            this.header = header;
            this.people = people;
        }

        public static PeopleMsg Deserialize(MessageDeserializer deserializer) => new PeopleMsg(deserializer);

        private PeopleMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.people, PersonMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.people);
            serializer.Write(this.people);
        }

        public override string ToString()
        {
            return "PeopleMsg: " +
            "\nheader: " + header.ToString() +
            "\npeople: " + System.String.Join(", ", people.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
